import Header from "@/components/Header"
import "./globals.css"
import { Exo_2 } from "next/font/google"

const exo = Exo_2({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${exo.className} bg-slate-50 text-gray-950 h-[5000px] pt-40 sm:pt-48`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
