import "./globals.css"
import { Inter } from "next/font/google"
import { Exo_2 } from "next/font/google"

const exo = Exo_2({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={exo.className}>{children}</body>
    </html>
  )
}
